### ISSUE TITLE
Switch to micromamba for CI

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/cookiecutter-mdakit#140]
This is a follow-up from a discussion with @fiona-naughton this morning. It looks like setup-miniconda is just problematic (it fails in odd ways with Python 3.13).

In the core library and increasingly in other places we are switching to using micromamba. It may be better to switch to it?

**Comment by lilyminium** [comment]
The joys of package managers. Sure, sounds good to me.

**Comment by orbeckst** [comment]
In the meantime, as long as we're still using [conda-incubator/setup-miniconda](https://github.com/conda-incubator/setup-miniconda): if we want to bump the version to 4, then we seem to have to use something like
```yaml
    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - name: Install conda dependencies
      uses: conda-incubator/setup-miniconda@v4
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: devtools/conda-envs/test_env.yaml
        add-pip-as-python-dependency: true

        miniforge-version: latest
        use-mamba: true
        channels: conda-forge

        activate-environment: mdaencore-test
        auto-update-conda: true
        auto-activate-base: false
        show-channel-urls: true


    - name: Install MDAnalysis version
      uses: MDAnalysis/install-mdanalysis@main
      with:
        version: ${{ matrix.mdanalysis-version }}
        install-tests: true
        installer:  conda 
        shell: bash  -l {0} 
```
namely `installer:  conda`. In PR https://github.com/MDAnalysis/mdaencore/pull/76 I found that the Windows builds would fail if it was set to `mamba`. The `mamba install` step would just not happen (silently!), see https://github.com/MDAnalysis/mdaencore/pull/76#issuecomment-4315051743 .
