### ISSUE TITLE
Add black configuration consistent with other tools?

### ISSUE THREAD

**Issue by RMeli** [MDAnalysis/cookiecutter-mdakit#73]
`pyproject.toml`:

```toml
[tool.black]
line-length = 80
extend-exclude = "versioneer.py"
```
